<?php
/**
 * about.php
 *
 * @author Wasp.io
 * @version 2.1.6
 * @date 03-Oct-2014
 * @package Wasp for Wordpress
 **/
?>
<div class="wrap">

    <h2>About Wasp.io</h2>
    
    <div style="width: 100%; float: none;">
        <div style="width: 50%; float: left;">
            <img src="https://wasp.io/assets/img/homepage/wasp-dash.png" style="max-width: 100%;" />
        </div>
        <div style="float: left; width: 50%;">
            <h3>Insanely detailed bug tracking</h3>
            <p>Wasp.io automatically tracks errors generated by your applications, intelligently notifies your team, and provides realtime data feeds of errors and activity for all of your websites.<br /><br />Add unlimited users, unlimited projects, and unlimited awesome to manage your web projects.</p>
            <p><a href="https://wasp.io/register?utm_source=wordpress&utm_medium=admin&utm_campaign=wordpress" target="_blank">Click here</a> to get started if you haven't already, or to login and check errors.</p>
        </div>
            <hr />
    </div>
    <div style="width: 100%; border-top: 1px dotted #333; padding-top: 3%; clear:both;">
        <div style="width: 50%; float: left;">
            <h3>Anywhere. Anytime.</h3>
            <p>Get realtime error reporting about all of your projects whether you're at the desk or on the move between clients.<br /><br />Wasp gives you as many or as few notifications about your projects' errors. Just adjust the message types in your user settings menu and we'll buzz you only when you want us to.</p>
            
            <p class="submit">
                <a href="#" class="button button-primary" style="background: #f1592a; width: 100%; padding: 10px 12px 10px 10px; height: auto; text-align: center; font-size: 21px; border:none;"  onClick="window.open('https://wasp.io/register?utm_source=wordpress&utm_medium=admin&utm_campaign=wordpress');return false;">Sign me up</a>
            </p>
        </div>
        <div style="float: left; width: 50%;">
            <img src="https://wasp.io/assets/img/homepage/mobiles.png" style="max-width: 90%;" />
        </div>
    </div>
    
</div>