<?php
/**
 * about.php
 *
 * @author Wasp.io
 * @version 2.1.6
 * @date 03-Oct-2014
 * @package Wasp for Wordpress
 **/
?>
<div class="wrap js-replace-frame">

    <h2>About Wasp.io</h2>
    
    <p>Wasp.io automatically tracks errors generated by your applications, intelligently notifies your team, and provides realtime data feeds of errors and activity for all of your websites.</p>
    
    <p>Add unlimited users, unlimited projects, and unlimited awesome to manage your web projects.</p>
    
    <p><a href="#" class="js-show-wasp">Click here</a> to get started if you haven't already, or to login and check errors.</p>
    
</div>
<script>
jQuery(document).ready(function($){
    $(document.body).on('click', 'a.js-show-wasp', function(event){
        event.preventDefault();
        var replacement = '<iframe class="js-wasp" src="https://wasp.io/register?utm_source=wordpress&utm_medium=admin&utm_campaign=wordpress" frameborder="0" style="overflow:hidden;height:100%;width:100%" height="900px" width="100%"></iframe>';
        $('.js-replace-frame').html(replacement);
        $('.js-wasp').css({'display' : 'block', 'height' : '800px', 'width' : '100%', 'margin': 'auto'});
    });
});
</script>