<?php
/**
 * about.php
 *
 * @author Wasp.io
 * @version 2.1.6
 * @date 03-Oct-2014
 * @package Wasp for Wordpress
 **/
?>
<div class="wrap">

    <h2>About Wasp.io</h2>
    
    <p>Wasp.io automatically tracks errors generated by your applications, intelligently notifies your team, and provides realtime data feeds of errors and activity for all of your websites.</p>
    
    <p>Add unlimited users, unlimited projects, and unlimited awesome to manage your web projects.</p>
    
    <p><a href="https://wasp.io/register?utm_source=wordpress&utm_medium=admin&utm_campaign=wordpress" target="_blank">Click here</a> to get started if you haven't already, or to login and check errors.</p>
    
</div>